name: nestiverse
description: Nestiverse revolutionizes the way people travel and stay by allowing individuals to rent unique accommodations from local hosts, offering a personalized and authentic experience that goes beyond traditional hotels.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  image_picker: ^1.0.4 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/fonts/

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCerealBlack.ttf
        - asset: assets/fonts/AirbnbCerealBold.ttf
        - asset: assets/fonts/AirbnbCerealBook.ttf
        - asset: assets/fonts/AirbnbCerealExtraBold.ttf
        - asset: assets/fonts/AirbnbCerealLight.ttf
        - asset: assets/fonts/AirbnbCerealMedium.ttf